export PATH="/usr/local/bin:$PATH"

# brew doc recommended
export PATH="$HOME/.bin:$PATH"

source $HOME/dotfiles/shell/alias.sh
source $HOME/dotfiles/shell/utils.sh
source $HOME/dotfiles/shell/prompt.sh # Pure by Sindre Sorhus

export EDITOR="/usr/local/bin/nvim"

# source plugins
source $HOME/dotfiles/shell/plugins/z.sh
source $HOME/dotfiles/shell/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# asdf
autoload -Uz compinit && compinit
. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash

# hub alias
eval "$(hub alias -s)"

# fzf vim settings
# Setting fd as the default source for fzf
export FZF_DEFAULT_COMMAND='fd --type f'

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

[ -n "$PS1" ] && sh ~/.config/plug/stellarized/shell/stellarized_dark.sh
