cask_args appdir: '/Applications'

tap 'homebrew/services'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/science'



brew 'git'

brew 'hub'

brew 'tig'

brew 'yarn'

brew 'mas'



brew 'coreutils'

cask '1password'

cask 'dropbox'

cask 'imageoptim'

cask 'transmission'

cask 'spectacle'
