cask_args appdir: '/Applications'

tap 'homebrew/services'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/science'

brew 'git'

brew 'hub'

brew 'tig'

brew 'yarn'

brew 'mas'

brew 'neovim'

brew 'fd'

brew 'fzf'

brew 'kakoune'

brew 'coreutils'

cask 'dropbox'

cask 'transmission'

cask 'spectacle'
