# plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload config %{
  set-option global plug_always_ensure true
  hook global WinSetOption filetype=plug %{
    remove-highlighter buffer/numbers
    remove-highlighter buffer/matching
    remove-highlighter buffer/wrap
    remove-highlighter buffer/show-whitespaces
  }
}

plug "ul/kak-lsp" do %{
  cargo build --release --locked
  cargo install --force --path . # `--path .' is needed by recent versions of cargo
} config %{
    evaluate-commands %sh{kak-lsp --kakoune -s $kak_session}
    set-option window lsp_auto_highlight_references true
    set-option window lsp_hover_anchor true
    set-face window DiagnosticError default+u
    set-face window DiagnosticWarning default+u

    hook global KakEnd .* lsp-exit
}


plug "alexherbo2/auto-pairs.kak" %{
  map global user s ': auto-pairs-surround <lt> <gt><ret>' -docstring 'Surround'
  hook global WinCreate .* %{ auto-pairs-enable }
  hook global WinSetOption filetype=(html|javascript|typescript) %{
    set-option -add buffer auto_pairs < >
  }
}

plug "occivink/kakoune-filetree" %{
  set-option global filetree_find_cmd 'fd --type file .'
}

# source extra
evaluate-commands %sh{
  for file in "$HOME"/.config/kak/extra/*.kak; do
  	printf "%s\n" "try %{
    	source '$file'
    	echo -debug 'sourced $file'
  	} catch %{
    	echo -debug %val{error}
  	} catch %{
    	echo -debug '[error] could not source $file'
  	}"
	done
}

# options
set-option global ui_options ncurses_assistant=cat
set-option global tabstop 2
set-option global indentwidth 2
set-option global incsearch true
set-option global scrolloff 10,10
set-option global grepcmd 'rg --column -with-filename --smart-case'

colorscheme gruvbox
add-highlighter global/ show-matching
add-highlighter global/ number-lines -hlcursor -separator ' '
add-highlighter global/ wrap -word -marker "↳ "

# commands
define-command find -params 1 -shell-script-candidates 'fd --type file' 'edit %arg(1)'
define-command strip-whitespace -params 0 %{ execute-keys -draft \%s\h+$<ret>d }

# mappings
map global normal ';' ':'
map global normal ':' ';'
map global normal ',' '<space>'
map global normal '<space>' ','
map global normal { [p
map global normal } ]p

map global goto n '<esc>: buffer-next<ret>'     -docstring 'next buffer'
map global goto p '<esc>: buffer-previous<ret>' -docstring 'previous buffer'

map global user f ': find '                     -docstring 'find files'
map global user p '!pbpaste<ret>'               -docstring 'paste from system keyboard'
map global user y '<a-|>pbcopy<ret>'            -docstring 'yank to system keyboard'
map global user / ': grepmenu '                 -docstring 'grepmenu <pattern> <target>'

# hooks
# <k><j> -> esc
hook global InsertChar j %{
  try %{
    exec -draft hH <a-k>kj<ret> d
    exec <esc>
}}

# cycle completion candidates with <tab> / <s-tab>
hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <s-tab> <c-p> }
hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <s-tab> <c-p> }

hook global KakBegin .* idsession

# filetype specifics
hook global WinSetOption filetype=(javascript|typescript) %{
  set-option buffer formatcmd 'prettier --parser=babylon'
  set-option buffer lintcmd 'eslint --config .eslintrc.js --format=node_modules/eslint-formatter-kakoune'
  lint-enable
  lint
  hook buffer BufWritePost .* %{ lint; format }
}

define-command -override -docstring "flygrep: run grep on every key" \
flygrep %{
    edit -scratch *grep*
    prompt "flygrep: " -on-change %{
        flygrep-call-grep %val{text}
    } nop
}

define-command -override flygrep-call-grep -params 1 %{ evaluate-commands %sh{
    length=$(printf "%s" "$1" | wc -m)
    [ -z "${1##*&*}" ] && text=$(printf "%s\n" "$1" | sed "s/&/&&/g") || text="$1"
    if [ ${length:-0} -gt 2 ]; then
        printf "%s\n" "info"
        printf "%s\n" "evaluate-commands %&grep '$text'&"
    else
        printf "%s\n" "info -title flygrep %{$((3-${length:-0})) more chars}"
    fi
}}
