#!/bin/sh

cd ~
curl --remote-name https://raw.githubusercontent.com/jssee/dotfiles/master/scripts/bootstrap
curl --remote-name https://raw.githubusercontent.com/jssee/dotfiles/master/Brewfile
/usr/bin/env bash bootstrap 2>&1 | tee ~/bootstrap.log
