#!/bin/sh

cd ~
curl --remote-name https://raw.githubusercontent.com/jssee/dotfiles/rcm/Brewfile
curl --remote-name https://raw.githubusercontent.com/jssee/dotfiles/rcm/scripts/bootstrap
/usr/bin/env bash bootstrap 2>&1 | tee ~/bootstrap.log
